<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Invoice #{{ $order->id }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { font-family: Arial, sans-serif; font-size: 14px; color: #111; }
        .wrap { max-width: 900px; margin: 20px auto; padding: 20px; border: 1px solid #eee; }
        .row { display:flex; justify-content:space-between; gap:16px; }
        h1 { margin: 0 0 6px; font-size: 22px; }
        .muted { color:#666; }
        table { width:100%; border-collapse: collapse; margin-top: 16px; }
        th, td { border: 1px solid #eee; padding: 10px; text-align:left; }
        th { background:#fafafa; }
        .right { text-align:right; }
        .badge { display:inline-block; padding:4px 8px; border-radius: 999px; font-size:12px; }
        .paid { background:#e7f7ec; color:#136f2d; }
        .pending { background:#fff4e5; color:#8a5a00; }
        .footer { margin-top: 18px; font-size: 12px; color:#666; }
    </style>
</head>
<body>
<div class="wrap">
    <div class="row">
        <div>
            <h1>Invoice #{{ $order->id }}</h1>
            <div class="muted">Date: {{ $order->created_at->format('Y-m-d H:i') }}</div>
            <div class="muted">Customer: {{ $order->user?->name }} ({{ $order->user?->email }})</div>
        </div>

        <div class="right">
            @php $isPaid = (bool)($order->paid_at ?? false); @endphp
            <div class="badge {{ $isPaid ? 'paid' : 'pending' }}">
                {{ $isPaid ? 'PAID' : 'PENDING PAYMENT' }}
            </div>
            @if($isPaid)
                <div class="muted" style="margin-top:6px;">
                    Paid at: {{ \Illuminate\Support\Carbon::parse($order->paid_at)->format('Y-m-d H:i') }}
                </div>
                @if(!empty($order->payment_method))
                    <div class="muted">Method: {{ $order->payment_method }}</div>
                @endif
            @endif
        </div>
    </div>

    <table>
        <thead>
        <tr>
            <th>Product</th>
            <th class="right">Price</th>
            <th class="right">Qty</th>
            <th class="right">Subtotal</th>
        </tr>
        </thead>
        <tbody>
        @foreach($order->items as $item)
            <tr>
                <td>{{ $item->product?->name ?? ('Product #' . $item->product_id) }}</td>
                <td class="right">${{ number_format(($item->price ?? 0) / 100, 2) }}</td>
                <td class="right">{{ $item->quantity }}</td>
                <td class="right">
                    ${{ number_format((($item->price ?? 0) * $item->quantity) / 100, 2) }}
                </td>
            </tr>
        @endforeach
        </tbody>
        <tfoot>
        <tr>
            <th colspan="3" class="right">Total</th>
            <th class="right">${{ number_format(($order->total ?? 0) / 100, 2) }}</th>
        </tr>
        </tfoot>
    </table>

    <div class="footer">
        This invoice is generated by the system. Payment simulation only (task requirement).
    </div>
</div>
</body>
</html>
