<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Invoice #{{ $order->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        .header { margin-bottom: 18px; }
        .row { display: flex; justify-content: space-between; }
        .muted { color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { padding: 8px; border-bottom: 1px solid #ddd; }
        th { text-align: left; background: #f5f5f5; }
        .right { text-align: right; }
        .total { font-size: 14px; font-weight: bold; }
        .badge { display:inline-block; padding: 4px 8px; border-radius: 999px; background: #e7f7ec; color:#0a7a2f; font-weight: 700; font-size: 11px; }
        .badge-warning { display:inline-block; padding: 4px 8px; border-radius: 999px; background: rgb(254 249 195 / var(--tw-bg-opacity, 1)); color:rgb(133 77 14 / var(--tw-text-opacity, 1)); font-weight: 700; font-size: 11px; }
        .footer { margin-top: 18px; font-size: 11px; color:#666; }
    </style>
</head>
<body>

<div class="header">
    <div class="row">
        <div>
            <h2 style="margin:0;">Shop-Cart</h2>
            <div class="muted">Receipt / Invoice</div>
        </div>
        <div style="text-align:right;">
            <div><strong>Invoice #{{ $order->id }}</strong></div>
            <div class="muted">
                Date: {{ optional($order->created_at)->format('Y-m-d H:i') ?? '-' }}
            </div>
            <div style="margin-top:6px;">
                @php
    $isPaid = strtoupper($order->status ?? 'PAID') === 'PAID';
@endphp

<span class="{{ $isPaid ? 'badge' : 'badge-warning' }}">
 {{ strtoupper($order->status ?? 'PAID') }}
                </span>
            </div>
        </div>
    </div>

    <hr style="border:none;border-top:1px solid #ddd;margin:12px 0;">

    <div class="row">
        <div>
            <div><strong>Billed To</strong></div>
            <div>{{ $order->user->name ?? 'Customer' }}</div>
            <div class="muted">{{ $order->user->email ?? '' }}</div>
        </div>
        <div style="text-align:right;">
            <div><strong>Total</strong></div>
            <div class="total">${{ number_format(($order->total ?? 0) / 100, 2) }}</div>
        </div>
    </div>
</div>

<table>
    <thead>
    <tr>
        <th>Product</th>
        <th class="right">Price</th>
        <th class="right">Qty</th>
        <th class="right">Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @foreach($order->items as $it)
        @php
            $price = $it->price ?? 0;
            $qty = $it->quantity ?? 0;
            $subtotal = $price * $qty;
        @endphp
        <tr>
            <td>{{ $it->product->name ?? ('Product #'.$it->product_id) }}</td>
            <td class="right">${{ number_format($price / 100, 2) }}</td>
            <td class="right">{{ $qty }}</td>
            <td class="right">${{ number_format($subtotal / 100, 2) }}</td>
        </tr>
    @endforeach
    </tbody>
    <tfoot>
    <tr>
        <th colspan="3" class="right">Total</th>
        <th class="right">${{ number_format(($order->total ?? 0) / 100, 2) }}</th>
    </tr>
    </tfoot>
</table>

<div class="footer">
    This is a simulated receipt for your university project (Shop-Cart).<br>
    Generated by Laravel + DomPDF.
</div>

</body>
</html>
